Architecture:
  Backbone:
    layers: 34
    name: ResNet
  Head:
    fc_decay: 0.0001
    name: CTCHead
  Neck:
    encoder_type: rnn
    hidden_size: 256
    name: SequenceEncoder
  Transform: null
  algorithm: CRNN
  model_type: rec
Eval:
  dataset:
    data_dir: data/paddleocr_training
    label_file_list:
    - data/paddleocr_training/val_list.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    batch_size_per_card: 8
    drop_last: false
    num_workers: 4
    shuffle: false
Global:
  cal_metric_during_train: true
  character_dict_path: data/paddleocr_training/dict.txt
  checkpoints: null
  debug: false
  distributed: false
  epoch_num: 100
  eval_batch_step:
  - 0
  - 100
  infer_img: null
  infer_mode: false
  log_smooth_window: 20
  max_text_length: 25
  pretrained_model: null
  print_batch_step: 10
  save_epoch_step: 10
  save_inference_dir: null
  save_model_dir: models/pinball_ocr
  use_gpu: true
  use_space_char: false
  use_visualdl: false
Loss:
  name: CTCLoss
Metric:
  main_indicator: acc
  name: RecMetric
Optimizer:
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
    name: Cosine
    warmup_epoch: 2
  name: Adam
  regularizer:
    factor: 0.0001
    name: L2
PostProcess:
  name: CTCLabelDecode
Train:
  dataset:
    data_dir: data/paddleocr_training
    label_file_list:
    - data/paddleocr_training/train_list.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - CTCLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 32
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    batch_size_per_card: 8
    drop_last: true
    num_workers: 4
    shuffle: true
